**fancy indexing**:- when we want to print nomn-continues colums of array. we use fancy

In [2]:
import numpy as np

In [3]:
arr8=np.arange(24).reshape(6,4)
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

i want to acces only row2,row 2 and row 4.

In [4]:
arr8[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [8]:
arr8[[0,2],[1,3]]

array([ 1, 11])

In [11]:
arr8[[3,3,5,5],[1,3,1,3]].reshape(2,2)

array([[13, 15],
       [21, 23]])

In [12]:
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
arr8[[0,1,3,4,0,5],[0,3,0,1,2,0]].reshape(3,2)

array([[ 0,  7],
       [12, 17],
       [ 2, 20]])