In [1]:
import numpy as np

In [3]:
arr=np.random.randint(low=1,high=100,size=20).reshape(4,5)
arr

array([[55, 87, 10, 50, 92],
       [31, 40, 91, 37,  7],
       [38, 38, 75, 56, 10],
       [20, 95, 63,  3, 27]])

this is boolean array

In [4]:
arr>50

array([[ True,  True, False, False,  True],
       [False, False,  True, False, False],
       [False, False,  True,  True, False],
       [False,  True,  True, False, False]])

overlaping the arr>50 with arr. it mean when (arr>50) condition become true the arr print only those elements

In [5]:
arr[arr>50]

array([55, 87, 92, 91, 75, 56, 95, 63])

we make two coditions one check that element is greater than 50 and is it odd.

In [6]:
arr[(arr>50) & (arr%2!=0)]

array([55, 87, 91, 75, 95, 63])

we replace 0 on the place of those elements which is greter than 50 and also odd numbers.

In [8]:
arr[(arr>50) & (arr%2!=0)]=0
arr

array([[ 0,  0, 10, 50, 92],
       [31, 40,  0, 37,  7],
       [38, 38,  0, 56, 10],
       [20,  0,  0,  3, 27]])