In [3]:
import numpy as np

In [5]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])

In [6]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

vector multiplication

In [7]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

scalar multiplication

In [8]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [9]:
arr1>3

array([False, False, False,  True,  True,  True])

In [10]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

In [11]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [12]:
arr1.dot(arr2)

154

Matrix multiplication works only if:


(m×n)⋅(n×p)

Columns of first matrix = Rows of second matrix

If they don’t match →  error

In [13]:
arr1.dot(arr3)

ValueError: shapes (6,) and (2,3) not aligned: 6 (dim 0) != 2 (dim 0)

In [14]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [15]:
arr4.max()

11

In [16]:
arr4.min()

6

In [17]:
arr4.max(axis=0)

array([10, 11])

In [19]:
arr4.max(axis=1)

array([ 7,  9, 11])

In [20]:
arr4.min(axis=0)

array([6, 7])

In [21]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [22]:
arr4.sum()

51

In [23]:
arr4.sum(axis=0)

array([24, 27])

In [24]:
arr4.sum(axis=1)

array([13, 17, 21])

In [25]:
arr4.mean()

8.5

This difference comes from:

🔹 Object-Oriented Programming (OOP)

You are studying OOP right now 👀

arr4.min() → Method call (object-oriented style)

np.median(arr4) → Functional style

In [26]:
np.median(arr4)

8.5

In [27]:
arr4.std()

1.707825127659933

In [28]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [29]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])