In [1]:
import numpy as np


In [4]:
np.random.random()

0.06494381329015919

In [10]:
np.random.seed(5)
np.random.random()

0.22199317108973948

In [16]:
np.random.uniform(1,100)

76.82487779155124

In [18]:
np.random.uniform(1,100,10).reshape(2,5)

array([[30.31191334, 63.25000298, 58.40394321, 60.39299047, 27.31609264],
       [29.18390218, 26.10523237, 33.42883082, 15.27226576, 17.39567326]])

In [34]:
np.random.randint(1,10,5)

array([2, 6, 8, 1, 7], dtype=int32)

In [37]:
a = np.random.randint(1,10,6)
a

array([1, 6, 3, 1, 8, 8], dtype=int32)

In [38]:
np.max(a)

np.int32(8)

In [39]:
np.min(a)

np.int32(1)

In [40]:
np.argmax(a) # index of max value

np.int64(4)

In [41]:
np.argmin(a) # index of min value

np.int64(0)

In [45]:
a = np.random.randint(1,10,6)
a

array([7, 5, 6, 3, 9, 9], dtype=int32)

In [46]:
a[a%2==1]=-1 # change all even numbers to -1
a

array([-1, -1,  6, -1, -1, -1], dtype=int32)

In [47]:
a = np.random.randint(1,50,6)
a

array([34, 29, 16,  7, 36, 48], dtype=int32)

In [ ]:
np.where(a%2==1, -1, a) # change all odd numbers to -1, keep even numbers as they are

array([34, -1, 16, -1, 36, 48], dtype=int32)

In [52]:
a

array([34, 29, 16,  7, 36, 48], dtype=int32)

In [51]:
out = np.where(a%2==1, -1, a)
out

array([34, -1, 16, -1, 36, 48], dtype=int32)

In [53]:
a = np.random.randint(1,50,10)
a

array([21,  9, 33, 19, 14, 29, 48, 19, 18, 23], dtype=int32)

In [54]:
a = np.sort(a)
a

array([ 9, 14, 18, 19, 19, 21, 23, 29, 33, 48], dtype=int32)

In [55]:
np.percentile(a, 25) # 25th percentile

np.float64(18.25)

In [56]:
np.percentile(a, 50) # 50th percentile (median)

np.float64(20.0)

In [57]:
np.percentile(a, 99.8) # 99.8th percentile

np.float64(47.72999999999999)