In [1]:
import numpy as np


In [4]:
arr4=np.arange(6,12).reshape(3,2)
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

array dimentions

In [5]:
arr4.ndim

2

**revel()**: we can change dimention of array from high dimention into 1 dimention.

In [ ]:
arr4.ravel()

array([ 6,  7,  8,  9, 10, 11])

**transpoose**: convert rows into colums

In [14]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

**stacking**:  make one array from two arrays .(comn=bine arrays) in vertical and horizental both

In [17]:
arr5=np.arange(12,18).reshape(2,3)
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [20]:
arr3=np.arange(6).reshape(2,3)
arr3

array([[0, 1, 2],
       [3, 4, 5]])

horizental 

In [21]:
np.hstack((arr3,arr5))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

vertical

In [22]:
np.vstack((arr3,arr5))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

**spliting**: split array into two ways, horizental and verticals

In [25]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

vetical split

In [23]:
np.vsplit(arr3,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

horizental

In [24]:
np.hsplit(arr3,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]